# Generated by Django 3.1 on 2020-08-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Parliamentary_Constituencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('constituency_number', models.CharField(max_length=10)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.states', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Parliamentary_Constituency',
                'verbose_name_plural': 'Parliamentary_Constituencies',
            },
        ),
        migrations.CreateModel(
            name='Assembly_Constituencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('constituency_number', models.CharField(max_length=10)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.states', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Assembly_Constituency',
                'verbose_name_plural': 'Assembly_Constituencies',
            },
        ),
    ]
