# Generated by Django 3.1 on 2020-09-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(blank=True, max_length=500)),
                ('acronym', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('National Party', 'National Party'), ('State Party', 'State Party'), ('Regional Party', 'Regional Party')], max_length=100)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='')),
                ('founded', models.CharField(blank=True, max_length=200)),
                ('founder_name', models.CharField(blank=True, max_length=200)),
                ('president_name', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
            },
        ),
    ]
