# Generated by Django 3.1 on 2020-09-09 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0002_parties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Central_Legislatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Central_Legislature',
                'verbose_name_plural': 'Central_Legislatures',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(blank=True, max_length=100)),
                ('start_year', models.CharField(blank=True, max_length=100)),
                ('end_year', models.CharField(blank=True, max_length=100)),
                ('central_legislature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.central_legislatures', verbose_name='Central_Legislatures')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
            },
        ),
        migrations.CreateModel(
            name='State_Legislatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.states', verbose_name='State')),
            ],
            options={
                'verbose_name': 'State_Legislature',
                'verbose_name_plural': 'State_Legislatures',
            },
        ),
    ]
