# Generated by Django 3.1 on 2020-09-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0003_central_legislatures_state_legislatures_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sittings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting_name', models.CharField(blank=True, max_length=100)),
                ('start_year', models.CharField(blank=True, max_length=100)),
                ('end_year', models.CharField(blank=True, max_length=100)),
                ('state_legislature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.state_legislatures', verbose_name='State_Legislatures')),
            ],
            options={
                'verbose_name': 'Sitting',
                'verbose_name_plural': 'Sittings',
            },
        ),
    ]
