# Generated by Django 3.1 on 2020-09-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0005_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200)),
                ('assembly_constituency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.assembly_constituencies', verbose_name='Assembly_Constituency')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.candidate', verbose_name='Candidate')),
                ('central_legislature_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.central_legislatures', verbose_name='Central_Legislatures')),
                ('parliamentary_constituency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.parliamentary_constituencies', verbose_name='Parliamentary_Constituency')),
                ('party_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.parties', verbose_name='Party')),
                ('sitting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.sittings', verbose_name='Sittings')),
                ('state_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.states', verbose_name='State')),
                ('state_legislature_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.state_legislatures', verbose_name='State_Legislatures')),
                ('term_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.term', verbose_name='Term')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
            },
        ),
    ]
