# Generated by Django 3.1 on 2020-09-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0006_candidature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parliamentary_Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(blank=True, max_length=100)),
                ('end_date', models.CharField(blank=True, max_length=100)),
                ('central_legislature_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.central_legislatures', verbose_name='Central_Legislatures')),
                ('term_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.term', verbose_name='Term')),
            ],
            options={
                'verbose_name': 'Parliamentary_Session',
                'verbose_name_plural': 'Parliamentary_Sessions',
            },
        ),
        migrations.CreateModel(
            name='Assembly_Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(blank=True, max_length=100)),
                ('end_date', models.CharField(blank=True, max_length=100)),
                ('sitting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.sittings', verbose_name='Sittings')),
                ('state_legislature_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.state_legislatures', verbose_name='State_Legislatures')),
            ],
            options={
                'verbose_name': 'Assembly_Session',
                'verbose_name_plural': 'Assembly_Sessions',
            },
        ),
    ]
