# Generated by Django 3.1 on 2020-09-29 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0008_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=300)),
                ('date', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(max_length=400)),
                ('candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.candidate', verbose_name='Participants')),
                ('central_legislature_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.central_legislatures', verbose_name='Central_Legislatures')),
                ('session_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.parliamentary_sessions', verbose_name='Parliamentary_Sessions')),
                ('term_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.term', verbose_name='Term')),
            ],
            options={
                'verbose_name': 'Debate',
                'verbose_name_plural': 'Debates',
            },
        ),
    ]
