# Generated by Django 3.1 on 2020-09-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0010_auto_20200930_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('ministry', models.CharField(blank=True, max_length=300)),
                ('date', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(max_length=400)),
                ('assembly_session_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.assembly_sessions', verbose_name='Assembly_Sessions')),
                ('candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.candidate', verbose_name='Introducer')),
                ('central_legislature_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.central_legislatures', verbose_name='Central_Legislatures')),
                ('parliamentary_session_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.parliamentary_sessions', verbose_name='Parliamentary_Sessions')),
                ('sitting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.sittings', verbose_name='Sittings')),
                ('state_legislature_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.state_legislatures', verbose_name='State_Legislatures')),
                ('term_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.term', verbose_name='Term')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
    ]
