# Generated by Django 3.1 on 2020-10-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0011_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='link',
            field=models.URLField(default='Not available', max_length=400),
            preserve_default=False,
        ),
    ]
