# Generated by Django 3.1 on 2020-10-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0014_auto_20201009_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='link',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='debates',
            old_name='link',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='link',
            new_name='source',
        ),
    ]
