# Generated by Django 3.1 on 2020-10-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0015_auto_20201009_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_signed_days', models.CharField(blank=True, max_length=200)),
                ('attendance_not_signed_days', models.CharField(blank=True, max_length=200)),
                ('candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.candidate', verbose_name='Member Name')),
                ('session_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.parliamentary_sessions', verbose_name='Parliamentary_Sessions')),
                ('term_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenGovCore.term', verbose_name='Term')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
            },
        ),
    ]
