# Generated by Django 3.1 on 2020-10-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0016_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='total_assets',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_liabilities',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
