# Generated by Django 3.1 on 2020-12-12 10:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0023_auto_20201102_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_constituencies',
            name='name_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='assembly_sessions',
            name='session_name_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='session_name'),
        ),
        migrations.AddField(
            model_name='bills',
            name='title_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='bills',
            name='type_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='type'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='name_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='central_legislatures',
            name='name_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='debates',
            name='title_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='debates',
            name='type_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='type'),
        ),
        migrations.AddField(
            model_name='parliamentary_constituencies',
            name='name_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='parliamentary_sessions',
            name='session_name_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='session_name'),
        ),
        migrations.AddField(
            model_name='parties',
            name='party_name_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='party_name'),
        ),
        migrations.AddField(
            model_name='questions',
            name='category_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='category'),
        ),
        migrations.AddField(
            model_name='questions',
            name='subject_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='subject'),
        ),
        migrations.AddField(
            model_name='state_legislatures',
            name='name_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='states',
            name='name_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
