# Generated by Django 3.1 on 2021-11-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0024_auto_20201212_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
