# Generated by Django 3.1 on 2021-11-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGovCore', '0025_bills_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='bills_file',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
